# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:02
from __future__ import unicode_literals

import apps.league.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20171026_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.league.models.Player.upload_to, verbose_name='Фотография'),
        ),
    ]
