# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20171026_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='teams',
        ),
        migrations.AlterField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(blank=True, to='league.Team', verbose_name='Команды'),
        ),
    ]
