# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20171026_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События в матче'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Тип события в матче', 'verbose_name_plural': 'Типы событий в матчах'},
        ),
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'verbose_name': 'Заявка команды на турнир', 'verbose_name_plural': 'Заявки команд на турнир'},
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='league.Team', verbose_name='Команда хозяев'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='league.Team', verbose_name='Команда гостей'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название турнира'),
        ),
    ]
