# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:33
from __future__ import unicode_literals

import apps.league.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20171103_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер фото: 350px*400px.', null=True, upload_to=apps.league.models.Player.upload_to, verbose_name='Фотография'),
        ),
    ]
