# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20171026_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция на поле', 'verbose_name_plural': 'Позиции на поле'},
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Position', verbose_name='Амплуа'),
        ),
    ]
