# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20171027_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например, "4 марта 2017, суббота. 17 Тур"', max_length=255, verbose_name='Название')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Tournament', verbose_name='Турнир')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Round', verbose_name='Тур'),
        ),
    ]
