# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20171030_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='match',
            name='match_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Round', verbose_name='Тур'),
        ),
    ]
