# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 12:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_auto_20171106_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='protocol',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='player',
            name='biography',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
