# Generated by Django 2.2.1 on 2020-06-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20171110_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeamApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(blank=True, to='league.Player', verbose_name='Игрок')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Заявка команды на турнир',
                'verbose_name_plural': 'Заявки команд на турнир',
            },
        ),
    ]
