# Generated by Django 2.2.1 on 2021-07-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20171110_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_technical_defeat',
            field=models.BooleanField(default=False, verbose_name='Техническое поражение'),
        ),
    ]
