# Generated by Django 2.2.1 on 2020-06-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_tournamentteamapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
    ]
