# Generated by Django 2.2.1 on 2021-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_match_is_technical_defeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='youtube_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на Youtube'),
        ),
    ]
