# Generated by Django 2.2.1 on 2021-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_match_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='match',
            name='youtube_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Id видео на Youtube'),
        ),
    ]
