# Generated by Django 2.2.1 on 2020-06-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_remove_tournament_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentPlayer',
        ),
    ]
