# Generated by Django 2.2.1 on 2020-07-05 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_delete_tournamentplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Минута'),
        ),
    ]
