# Generated by Django 2.2.1 on 2020-08-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_auto_20200705_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ('-pk',), 'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
    ]
