# Generated by Django 2.2.1 on 2021-06-20 09:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210620_1235'),
        ('league', '0021_auto_20200801_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название соревнования')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeamApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Competition', verbose_name='Соревнование')),
                ('players', models.ManyToManyField(blank=True, to='league.Player', verbose_name='Игрок')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Заявка команды на соревнование',
                'verbose_name_plural': 'Заявки команд на соревнования',
            },
        ),
        migrations.RemoveField(
            model_name='tournamentteamapplication',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournamentteamapplication',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tournamentteamapplication',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='round',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentTeamApplication',
        ),
        migrations.AddField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Competition', verbose_name='Соревнование'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Competition', verbose_name='Соревнование'),
        ),
        migrations.AddField(
            model_name='round',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Competition', verbose_name='Соревнование'),
        ),
    ]
