# Generated by Django 2.2.1 on 2021-06-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_auto_20210620_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
