# Generated by Django 2.2.1 on 2021-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_remove_player_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-pk',), 'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(to='league.Team', verbose_name='Текущие команды'),
        ),
    ]
