# Generated by Django 2.2.24 on 2021-11-24 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_auto_20210620_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_technical_defeat',
            field=models.BooleanField(default=False, verbose_name='Техническое поражение'),
        ),
        migrations.AddField(
            model_name='match',
            name='youtube_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Id видео на Youtube'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минута'),
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_from', models.IntegerField(blank=True, help_text='Если ввести 0, то будет считаться что игрок вышел в стартовом составе, иное значение - вышел на замену.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вышел на поле, минута')),
                ('played_to', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Играл до, минута')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Match', verbose_name='Матч')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Заявка на матч, протокол',
                'verbose_name_plural': 'Заявка на матч, протокол',
            },
        ),
    ]
