# Generated by Django 3.2.9 on 2021-11-29 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_matchlineup_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='substitute',
            field=models.BooleanField(default=False, verbose_name='Замена'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='played_to',
            field=models.IntegerField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Играл до, минута'),
        ),
    ]
