# Generated by Django 3.2.9 on 2021-11-30 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_auto_20211129_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='played_to',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Играл до, минута'),
        ),
    ]
