# Generated by Django 3.2.9 on 2021-12-06 11:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_alter_matchlineup_played_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchlineup',
            name='played_from',
        ),
        migrations.RemoveField(
            model_name='matchlineup',
            name='played_to',
        ),
        migrations.RemoveField(
            model_name='matchlineup',
            name='substitute',
        ),
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='event',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1-й тайм'), (2, '2-й тайм'), (3, 'Дополнительное время')], null=True, verbose_name='Тайм'),
        ),
        migrations.AddField(
            model_name='event',
            name='player_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_assigned', to='league.player', verbose_name='Связанный игрок'),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='start',
            field=models.BooleanField(default=False, verbose_name='Стартовый состав'),
        )
    ]
