# Generated by Django 3.2.9 on 2021-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_auto_20211206_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Стадион',
                'verbose_name_plural': 'Стадионы',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Матч окончен'),
        ),
    ]
