# Generated by Django 3.2.9 on 2021-12-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_auto_20211208_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.stadium', verbose_name='Стадион'),
        ),
    ]
