# Generated by Django 3.2.9 on 2022-01-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0034_auto_20211216_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='coach_team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_team_1', to='league.coach', verbose_name='Тренер команды 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='coach_team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_team_2', to='league.coach', verbose_name='Тренер команды 2'),
        ),
    ]
