# Generated by Django 3.2.9 on 2022-01-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0035_auto_20220111_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='например, "Сезон 20/21"', max_length=255, verbose_name='Название сезона')),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Спонсор')),
                ('is_current_season', models.BooleanField(default=False, verbose_name='Текущий сезон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.season', verbose_name='Сезон'),
        ),
    ]
