# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст')),
                ('phones', models.TextField(max_length=255, verbose_name='Телефон(ы)')),
                ('emails', models.TextField(max_length=255, verbose_name='E-Mail(ы)')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
