# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'E-Mail, на который отправляются данные формы контактов',
                'verbose_name_plural': 'E-Mail, на которые отправляются данные формы контактов',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='emails_contact_form',
            field=models.ManyToManyField(blank=True, to='contacts.ContactEmail'),
        ),
    ]
