# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_emails_contact_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactemail',
            options={'verbose_name': 'E-Mail формы контактов', 'verbose_name_plural': 'E-Mail формы контактов'},
        ),
    ]
