# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171205_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='emails_contact_form',
        ),
    ]
