# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carousel_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(help_text='Рекомендуемый размер: 1140px*400px', upload_to='carousel', verbose_name='Изображение'),
        ),
    ]
