# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lasttournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lasttournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
    ]
