# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bombardierspenaltiessettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BombardiersPenaltiesSettings',
            new_name='BombardiersPenaltiesTableSettings',
        ),
        migrations.AlterModelOptions(
            name='bombardierspenaltiestablesettings',
            options={'verbose_name': 'Таблица, бомбардиры, штрафники', 'verbose_name_plural': 'Таблица, бомбардиры, штрафники'},
        ),
    ]
