# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20171022_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='information_block_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст блока (html)'),
        ),
    ]
