# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
    ]
