# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20171030_1333'),
        ('home', '0005_auto_20171031_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombardiersPenaltiesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Tournament', verbose_name='Турнир')),
            ],
        ),
    ]
