# Generated by Django 2.0.5 on 2018-05-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20171110_1329'),
        ('home', '0009_auto_20180418_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_table', models.BooleanField(default=True, verbose_name='Показывать турнирную таблицу')),
                ('show_bombardiers', models.BooleanField(default=True, verbose_name='Показывать бомбардиров')),
                ('show_penalties', models.BooleanField(default=True, verbose_name='Показывать штрафников')),
                ('show_assistants', models.BooleanField(default=True, verbose_name='Показывать ассистентов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Виджеты',
                'verbose_name_plural': 'Виджеты',
            },
        ),
        migrations.RemoveField(
            model_name='bombardierspenaltiestablesettings',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='BombardiersPenaltiesTableSettings',
        ),
    ]
