# Generated by Django 2.2.1 on 2021-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180525_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.RemoveField(
            model_name='lasttournament',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='widgetssettings',
            name='tournament',
        ),
    ]
