# Generated by Django 2.2.1 on 2021-06-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_auto_20210620_1235'),
        ('home', '0011_auto_20210620_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetssettings',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Competition', verbose_name='Соревнование'),
        ),
        migrations.DeleteModel(
            name='LastTournament',
        ),
        migrations.AddField(
            model_name='lastcompetition',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Competition', verbose_name='Соревнование'),
        ),
    ]
