# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_block_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок текстового блока')),
                ('information_block_text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст блока')),
                ('contacts_block_html', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст блока "Контактная информация" (html)')),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Facebook')),
                ('vk_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка VK')),
                ('twitter_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Twitter')),
                ('google_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Google')),
                ('copyrights_block_html', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст блока копирайта (html)')),
            ],
        ),
    ]
