# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20171022_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Изображение')),
            ],
        ),
    ]
