# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20171027_1029'),
        ('settings', '0006_auto_20171026_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Персона', max_length=255, verbose_name='Заголовок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player', verbose_name='Игрок')),
            ],
        ),
    ]
