# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_personwidget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personwidget',
            options={'verbose_name': 'Виджет "Персона"', 'verbose_name_plural': 'Виджет "Персона"'},
        ),
    ]
